### PR TITLE
feat(watsonx.ai): Streaming

### PR DESCRIPTION
**Pull request by jfmartinez**

### CODE REVIEW

**Comment by anirudhaBapat** [comment]
Hey, you need to set these before calling `Invoke watsonx Generation Stream API` step. We do the same for `Invoke watsonx Generation API` see step 8 of Test model, otherwise you will get the error - 

```
{"status":400,"body":{"errors":[{"code":"json_validation_error","message":"Json document validation error: 'input' cannot be missing or empty in the request body","more_info":"https://cloud.ibm.com/apidocs/watsonx-ai"}],"trace":"11e5e3b5a63f09ef3c8e744f651be317","status_code":400}}
```

Screenshot 2024-07-11 at 9 36 32 AM

**Comment by jfmartinez** [comment]
Thanks @anibapat, Step 7 now steps the variables appropiately:

Screenshot 2024-07-11 at 1 21 16 PM

**Review by anirudhaBapat — APPROVED** [review]
LGTM! tested on dev020

**Comment by anirudhaBapat** [comment]
I think you need someone who has a write access, I have some odd GH public account issue which prevents me having that access. @jwm4 Can you review & approve?

**Review by jwm4 — APPROVED** [review]
Looks good + important, and Ani tested it.

**Pull request merged**
