### PR TITLE
chore: update watsonx spec and conv search for granite v2

### PR DESCRIPTION
**Pull request by sne3091**
Addresses https://bigblue.aha.io/features/LSABER-1679?active_tab=tasks#task_7340012418530350714

### CODE REVIEW

**Review by zach-shu — COMMENTED** [review]
Thanks a lot, Sneha. This PR looks good to me. I did some testing with the updated watsonx openapi spec and the actions JSON, and they worked as expected functionality-wise. 

The only issue I encountered was that the step to call watsonx extension in the `Invoke watsonx generation API` action couldn't be auto-filled. I had to manually configure that step. After I manually configured it, I tried downloading/uploading actions JSON and everything worked fine. I can see the JSON content difference was on the fields under `resolver.catalog.callout.internal.`. 

I recall that @rfazeli identified the same issue before. Do we have a solution for it?

**Comment by sne3091** [comment]
> I can see the JSON content difference was on the fields under resolver.catalog.callout.internal.

This time you may have encountered an issue because your previous watsonx.api spec was different? I updated the spec to upgrade from the beta version and added a bunch of newly supported params. That could have caused the diff in integration

**Comment by zach-shu** [comment]
> > I can see the JSON content difference was on the fields under resolver.catalog.callout.internal.
> 
> This time you may have encountered an issue because your previous watsonx.api spec was different? I updated the spec to upgrade from the beta version and added a bunch of newly supported params. That could have caused the diff in integration

I see. I also tried starting with a new Assistant and got the same issue.

**Review by jwm4 — APPROVED** [review]
The latest commit seems to fix the issues Zach raised, and it is all working and looks good to me!

**Review by zach-shu — APPROVED** [review]
Looks good to me now.

**Review by jwm4 — CHANGES_REQUESTED** [review]
Actually, it would be better if the other examples were updated to also be compatible with the new OpenAPI spec for wxai v1 GA.  (As Sneha pointed out on Slack)

**Review by jwm4 — APPROVED** [review]
Everything works and the README updates look good.

**Pull request merged**
